spring.application.name=student-managment
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=irakli
spring.datasource.password=mgug3606.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true